name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build node app
    environment: test
    runs-on: self-hosted

    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Check Version
        run: node --version && npm --version && docker --version
      
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            binyul11/learning-node.js:latest
            binyul11/learning-node.js:${{ github.sha }}
            binyul11/learning-node.js:${{ github.run_number }}
  deploy:
    name: Deploy with Docker Compose
    needs: build
    environment: test
    runs-on: self-hosted

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy with Docker Compose
        run: |
          docker compose pull
          docker compose up -d --remove-orphans
          docker compose ps